### ISSUE TITLE
[Question] Is the CheatBreakerAPINetHandler going to be released?

### ISSUE THREAD

**Issue by ShonP40** [CheatBreaker/CheatBreakerAPI#3]
Is the CheatBreakerAPINetHandler going to be released? and when?

**Comment by jhalt** [comment]
Yes, I'll probably end up open-sourcing the NetHandler code at some point, but I don't know when that will be just yet.

That codebase is particularly messy, even more so than this codebase, and I'm thinking of cleaning it up before opening it up to the public. Maybe not. We'll see.

As this is going to be a common question (e.g. #4), I'm going to leave this issue open until such time that the NetHandler repo is made available to the public.

Happy New Year
- Jonathan

**Comment by ShonP40** [comment]
Ok, thank you.
Happy New Year!

**Comment by ShonP40** [comment]
Btw, Can you compile and release the plugin for now please?

**Comment by bchubbs** [comment]
ShonP44, if you're not able to understand maven, or basic file compilation you should just delete your GitHub account.

**Comment by bchubbs** [comment]
> Btw, Can you compile and release the plugin for now please?

I'll be compiling this tomorrow. For anybody interested in the jar, DM me on Discord: Chubbs#6717. Note the plugin functionality is limited due to CB not being released. When the NetHandler is released, I'll update the jar.

Happy New Year.

**Comment by jhalt** [comment]
> I'll be compiling this tomorrow. For anybody interested in the jar, DM me on Discord: {removed}. Note the plugin functionality is limited due to CB not being released. When the NetHandler is released, I'll update the jar.
> 
> Happy New Year.

Hi, @bchubbs: I’ve removed your original reply, but quoted it above with redacted contact information.

You’re welcome to do that, but for safety reasons, you’ll need to open-source the code in order for me to allow you to post the JAR or your contact information here. Ideally, you can configure a GitHub build process for the release - but that is by no means required.

I hope you understand the reasoning behind this, and I appreciate your understanding.

**Comment by jhalt** [comment]
> I'll be compiling this tomorrow. For anybody interested in the jar, {removed contact information}. Note the plugin functionality is limited due to CB not being released. When the NetHandler is released, I'll update the jar.
> 
> Happy New Year.

Hi, @bchubbs: I’ve removed your original reply, but quoted it above with redacted contact information.

You’re welcome to do that, but for safety reasons, you’ll need to open-source the code in order for me to allow you to post the JAR or your contact information here. Ideally, you can configure a GitHub build process for the release - but that is by no means required.

I hope you understand the reasoning behind this, and I appreciate your understanding.

**Comment by bchubbs** [comment]
Yep, all good. I was just adding contact information to make the process easier. Anyway, the updated "functional" code will be in a public repo soon. The JAR will be there along with it.

**Comment by jhalt** [comment]
@bchubbs: No worries. Only issue I have is in the README, you’re suggesting people file bug reports with us for your compiled version of the plugin. We won’t provide support for it, and any issues introduced as a result of using an unofficial build are definitely out of scope for us. Even the version here is unmaintained and unsupported.

\- Jonathan

**Comment by jhalt** [comment]
@bchubbs: No worries. Only issue I have is that you’re suggesting that people file bug reports with us for your compiled version of the plugin. We won’t provide support for it, and any issues introduced as a result of using an unofficial build are definitely out of scope for us. Even the version here is unmaintained and unsupported.

\- Jonathan

**Comment by bchubbs** [comment]
I removed the support messages from repo & code.

**Comment by jhalt** [comment]
Thanks!

**Comment by M4T14SG4M3R** [comment]
Hi, i know that you are planning on releasing the Net API, did you got an estimated date of releasing? Like 1 month, 2, 3?

**Comment by ShonP40** [comment]
@jhalt I know that this is off topic but can you add me on Discord please? I want to ask you a couple of MC related questions.

My Discord username is ShonP40#8389

**Comment by TechOutTV** [comment]
Will this ever get released the CheatBreakerAPINetHandler, I have been waiting for a while for it to become public

**Comment by M4T14SG4M3R** [comment]
me too

**Comment by M4T14SG4M3R** [comment]
I have a little problem with the api, i have enabled the voice and when a player join to my channel, it says "*Nick* joined *channelname* channel. Press 'P'!, but when i press P it says "Voice chat is not supported!" and when i join a channel it says "Joined *channelname* channel. Press 'V' to talk!" But it still says "Voice chat is not supported" while i press P and in the michropone option it still says "Unknown"

**Comment by ShonP40** [comment]
Where did you get the NetHandler? or a working version of this API? @M4T14SG4M3R

**Comment by ghost** [comment]
Will their be a build happening any time soon? @jhalt

**Comment by M4T14SG4M3R** [comment]
Sadly the api is useless if you want to add voice to the server, i used it and only works for the other modules

**Comment by cProxi** [comment]
LunarBreaker is a team that I made quite a while ago after receiving both NetHandlers unofficially. Whilst this is very unofficial and has no claim to be official, it does work effectively. However both NetHandlers for Lunar Client as well as CheatBreaker are on there if you would like to check it out: https://github.com/LunarBreaker. As said above the Voice Chat doesn't work on CheatBreaker OR Lunar Client for reasons stated here: https://github.com/LunarBreaker/LunarBreakerAPI/issues/1.

**Comment by ShonP40** [comment]
Kinda forgot about this issue but yea, me & my team over at https://github.com/Offline-CheatBreaker (not affiliated) received the CB NetHandler unofficially years ago as well & We have our own open-source continuation of it on our GitHub.

So, I guess that this issue can be closed.
