### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by svenoo** [CheatBreaker/CheatBreakerAPI#5]
As I was looking through the code I saw that a depend called 'CheatBreaker NetHandler' was missing.

**Comment by Baitinq** [comment]
lol

**Comment by ShonP40** [comment]
Duplicate of #3

**Comment by bchubbs** [comment]
Jon said that he will probably end up open-sourcing the NetHandler code at some point, but we don't know when that will be just yet.

**Comment by jhalt** [comment]
Duplicate of #3. In addition, this has been clearly articulated at the bottom of the README:
https://github.com/CheatBreaker/CheatBreakerAPI/blob/master/README.md#approval-for-public-release
